ryonakano/reco

- src/Application.vala
- src/MainWindow.vala
- src/Views/CountDownView.vala
- src/Views/RecordView.vala
Fixes #34
```
(com.github.ryonakano.reco:6864): Gtk-CRITICAL **: 19:36:42.253: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed
```
> Save recordings when the app window is destroyed

- src/Views/CountDownView.vala
Fixes #45
1. If the countdown is paused, don't decrement the seconds.
2. If the countdown gets paused, cancel the Timeout callback.
3. If the countdown gets canceled, cancel the Timeout callback.
> Fix the behavior of the countdown timer when pausing/canceling it

- src/Views/WelcomeView.vala
* Remove unnecessary lines to restore the last state because they've already used `GLib.Settings.bind`
* Use `GLib.Settings.bind` more
* Rename `auto_save` to `auto_save_switch`
> WelcomeView: Use GLib.Settings.bind

- src/MainWindow.vala
We can keep the headerbar without the app name but show it in Multitasking View in this way
> MainWindow: Add window title

- src/Views/WelcomeView.vala
Not sure why I chose the word "Computer" for the label text, while I used "system" for the id text
> WelcomeView: Use the word 'System' to represent system sound

- com.github.ryonakano.reco.yml
If you choose AAC for the file format, the app crashes when you start recording and get the following error message:
```
** (com.github.ryonakano.reco:2): ERROR **: 17:01:02.062: Recorder.vala:118: The GStreamer element encoder was not created correctly
```
This PR adds `gst-libav` which should include `avenc_aac` but it does not work for some reason.
> Flatpak: Add runtime dependency gst-libav for avenc_aac

- src/Services/DeviceManager.vala
- src/Services/Recorder.vala
- Use `Gst.Device.create_element` instead of `Gst.Device.reconfigure_element` to remove double check for `Source`
- Explicit nullable
- Put `display_name` in quotation marks
> Recorder: Clean code

- com.github.ryonakano.reco.yml
- data/reco.gschema.xml
- src/Application.vala
- src/MainWindow.vala
- src/Views/WelcomeView.vala
Fixes #168
Supersedes #169
We no longer need write/read access to disks at all, and only get permission to the directories/files user selected in the file chooser
> Remove access permission to disks by default

- src/MainWindow.vala
- src/Views/RecordView.vala
- Set recording duration and then start recording
- Once completed, set duration to 0 and start recording again
- The remain time label still there with no decreasing its counter
> RecordView: Hide remaining time label when unnecessary

- src/MainWindow.vala
- src/Views/CountDownView.vala
- src/Views/RecordView.vala
- src/Views/WelcomeView.vala
From https://valadoc.org/gtk4/Gtk.StyleContext.html:
> Warning: StyleContext is deprecated since 4.10.
>
> `GtkStyleContext` stores styling information affecting a widget.
>
> Note:
> The relevant API has been moved to [class@Gtk.Widget] where applicable; otherwise, there is no replacement for querying the style machinery. Stylable UI elements should use widgets.
Regarding to `Gtk.StyleContext.add_provider_for_display`, it's not clear if it's deprecated or not from [the doc](https://docs.gtk.org/gtk4/type_func.StyleContext.add_provider_for_display.html) so leaving it as it is for now.
> GTK: Replace deprecated Gtk.StyleContext.add_class / remove_class

- src/StyleSwitcher.vala
It turns out that this is working as expected on Ubuntu 22.04 LTS at least
> StyleSwitcher: Let system-synced color preference available on any platforms

- README.md
- data/reco.desktop.in
- data/reco.metainfo.xml.in
This serves to remove some redundancy, give the descriptions of the application more clarity, and elaborate on functionality. If there is anything I missed, let me know.
> Reword and elaborate on metadata and descriptions

- src/Services/AbstractTimer.vala
Fixes #235
We're forgotting Source.remove and multiple GLib.Timeouts alive after pausing.
Also replace and correct useless (and wrong) remove flag.
> AbstractTimer: Fix double count up/down

- src/Application.vala
From https://docs.gtk.org/gtk4/class.Application.html
> GtkApplication will also automatically setup an icon search path for the default icon theme by appending “icons” to the resource base path.
> Application: Fix redundant load of icon

- src/Application.vala
This static method is not deprecated in Gtk4 at this moment actually and it seems to be an error in Vala:
https://docs.gtk.org/gtk4/type_func.StyleContext.add_provider_for_display.html https://gitlab.gnome.org/GNOME/vala/-/commit/e6bc168ce69b16437ac5556fe537675ab2cd189f
> Application: Remove TODO about deprecation of Gtk.StyleContext.add_provider_for_display

- build-aux/appcenter/com.github.ryonakano.reco.Devel.yml
- com.github.ryonakano.reco.yml
Flatpak External Data Checker seems to force this style, which is annoying though, so switch to it now to avoid manifest update and coding style update from being in one commit
> Flatpak: Omit quote when possible

- build-aux/appcenter/com.github.ryonakano.reco.Devel.yml
- com.github.ryonakano.reco.yml
I prefer archives for quick download but that should be a tiny difference in the modern fast networks
Leaving gst-livav as archive because its git is the single gstreamer repository which is big and waste of time and network traffic to download
> Flatpak: Use git for modules

- build-aux/appcenter/com.github.ryonakano.reco.Devel.yml
- com.github.ryonakano.reco.yml
From https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html:
> Note, "app-id" is deprecated and preserved only for backwards compatibility.
> Flatpak: Use id instead of deprecated app-id

- src/MainWindow.vala
- src/View/CountDownView.vala
- src/View/WelcomeView.vala
Getting delay length from GSettings here is just a waste of method call
> refactor: Obtain delay length from spinner directly instead of GSettings

- CONTRIBUTING.md
- README.md
As we did #308 and #310, we now target Flathub by default and optionally build for AppCenter.
> docs: Default for Flathub, optionally for AppCenter

- src/MainWindow.vala
- src/Model/Recorder.vala
- src/Util.vala
Fixes #289
- Include both start and end date time in filenames
- Remove redundant prefix "Recording from"
> feat: Improve filename

- src/Manager/DeviceManager.vala
Fixes #282
We're too strict to detect input/output devices and resulting ignoring Bluetooth devices.
I connect my AirPods Pro 2 to Fedora 43 and confirmed:
> fix: Support recording from Bluetooth devices
