ryonakano/reco

meson.build, src/Application.vala, src/MainWindow.vala, src/Views/RecordView.vala, src/Views/WelcomeView.vala
=> Make it possible to record

data/icons/128/com.github.ryonakano.reco.svg, data/icons/16/com.github.ryonakano.reco.svg, data/icons/24/com.github.ryonakano.reco.svg, data/icons/32/com.github.ryonakano.reco.svg, data/icons/48/com.github.ryonakano.reco.svg, data/icons/64/com.github.ryonakano.reco.svg, data/meson.build, meson/post_install.py
=> Have an app icon

src/Views/RecordView.vala, src/Views/WelcomeView.vala
Fixes #6 
* AAC
* FLAC
* MP3
* Ogg Vorbis
* Opus
=> Support more formats

src/Views/RecordView.vala, src/Views/WelcomeView.vala
=> Allow to set recording rength

data/Application.css, data/icons/record-completed-symbolic.svg, data/meson.build, src/Views/RecordView.vala, src/Views/WelcomeView.vala
=> Notify success of recording with a check mark

data/Application.css, src/Views/RecordView.vala
=> Add cancel_button and pause_button

src/MainWindow.vala, src/Views/CountDownView.vala
=> Allow to cancel/pause countdown before recording

meson.build, src/Application.vala, src/MainWindow.vala, src/Services/Recorder.vala, src/Views/RecordView.vala
Exclude recording stuff from UI related files
=> Recorder refactoring

src/Views/RecordView.vala
Fixes #40
idk why I added such a strange line here btw… :thinking:
=> Fix recording won't success when changing the file format

src/Services/Recorder.vala
=> Support recording both sounds from mic and from PC

data/com.github.ryonakano.reco.gschema.xml, src/Services/Recorder.vala, src/Views/WelcomeView.vala
=> Support three source selections

po/LINGUAS, po/extra/LINGUAS, po/extra/extra.pot, po/extra/tr.po, po/tr.po
=> Add Turkish translation

po/LINGUAS, po/extra/LINGUAS, po/extra/ru.po, po/ru.po
Here is the russian translation for recording app. Should be properly done, everything is ready.
=> Add Russian translation

src/Services/Recorder.vala
=> Recorder Cast as a new Enum instead of a row int

data/com.github.ryonakano.reco.gschema.xml, src/Services/Recorder.vala, src/Views/WelcomeView.vala
=> Recorder: Always record in stereo

data/com.github.ryonakano.reco.appdata.xml.in
=> AppData: Revive the old release notes

data/com.github.ryonakano.reco.gschema.xml, src/MainWindow.vala, src/Views/CountDownView.vala, src/Views/RecordView.vala, src/Views/WelcomeView.vala
The GSettings key `length` and `delay` should take only natural numbers, so we should make sure that
=> Use uint32 for length and delay

src/MainWindow.vala
Thanks tintou for this info: https://developer.gnome.org/gtk4/unstable/ch41s02.html#id-1.7.4.4.75
=> Follow API change of Gtk.FileChooser in GTK 4

src/Services/Recorder.vala
Fixes #82
Easier to fix than expected :blush:
=> Recorder: Remove temporary recordings on error

src/Services/Recorder.vala
=> Handle large indexes

src/Services/Recorder.vala
=> Inhibit sleeping while recording

src/Application.vala, src/MainWindow.vala
This would be much simpler and make it possible to lessen scopes
=> Use Gtk.Widget.key_press_event instead of SimpleAction

src/Application.vala, src/MainWindow.vala
Fixes #95
Revert (possibly) the cause of the building error in the linked issue. Not sure what's happening here because building locally and in GitHub Actions passes though.
=> Revert "Use Gtk.Widget.key_press_event instead of SimpleAction (#91)"

README.md, data/meson.build, meson.build
See also: https://mesonbuild.com/Reference-manual.html#join_paths
=> meson: Use '/' instead of join_path

data/reco.gschema.xml, meson.build, src/Services/DeviceManager.vala, src/Services/Recorder.vala, src/Views/WelcomeView.vala
* Support choosing a microphone to use for recording (fixes #75)
* Refresh microphone list on addition/removal
* Change how to detect recording sources
* Redesign: Separate Delay and Duration settings from Recording section as Timer section and put it under Recording section
=> Redesign the app

data/reco.gschema.xml, src/Services/Recorder.vala, src/Views/WelcomeView.vala
Change the current entry `device` to `source` and `microphone` to `device`
=> More accurate setting name

src/Views/WelcomeView.vala
=> WelcomeView: Ellipsize if device name is long

data/reco.gschema.xml, src/Services/DeviceManager.vala, src/Services/Recorder.vala, src/Views/WelcomeView.vala
=> Use Gst.Device.reconfigure_element instead of fetching device name

data/reco.gschema.xml, src/Services/Recorder.vala, src/Views/WelcomeView.vala
=> Replace AAC with ALAC

meson.build, meson_options.txt, src/Application.vala, src/MainWindow.vala, src/StyleSwitcher.vala
As suggested in https://github.com/elementary/appcenter-reviews/pull/296#issuecomment-1010240598
=> Check desktop environment on runtime

po/extra/pt.po, po/pt.po
Updated translations...
@ryonakano Happy new year!
=> Update Portuguese translation

data/reco.appdata.xml.in, src/MainWindow.vala
=> Use Gtk.MessageDialog instead of Granite.MessageDialog on other distros

data/meson.build, data/reco.metainfo.xml.in, po/extra/POTFILES
Same with https://github.com/ryonakano/konbucase/pull/96
- Rename to `.metainfo.xml.in` which recommended by fd.o
- Use "desktop-application" instead of deprecated "desktop" for `component` tag
- Add caption to screenshots
- Use fixed branch in screenshot URL
- Use fd.o standardized `brand` tag instead of `custom` tag by elementary
- Add `supports` tag
References:
- https://freedesktop.org/software/appstream/docs/sect-Metadata-Application.html
- https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
=> Metainfo: Rename and improve

data/reco.gschema.xml, src/Services/Recorder.vala, src/Views/WelcomeView.vala
This switch-case is foolish and totally unnecessary
=> Recorder: Clean code

data/reco.metainfo.xml.in
=> Fix typo, rewrited -> rewritten

src/MainWindow.vala, src/Services/Recorder.vala, src/Views/RecordView.vala, src/Widgets/LevelBar.vala
Addresses [this issue](https://github.com/ryonakano/reco/pull/193#issuecomment-1675594506):
=> LevelBar: Support pause and resume

data/reco.gschema.xml, src/Services/DeviceManager.vala, src/Services/Recorder.vala, src/Views/WelcomeView.vala
This is not something we should save in public
=> Internally store selected microphone

src/MainWindow.vala, src/Views/RecordView.vala
=> Fix Ctrl+Q quits the app without saving

README.md, data/reco.metainfo.xml.in
This sounds a bit nicer IMO - but I am not a native speaker, so I might be totally wrong xD
=> Reword string in metainfo

com.github.ryonakano.reco.yml, src/Views/WelcomeView.vala
=> WelcomeView: Show tooltip for each row

README.md, com.github.ryonakano.reco.yml, meson.build
Now it's released.
https://github.com/lcallarec/live-chart/releases/tag/1.10.0
=> Update live-chart and add limitation for 1.10.0 or above

src/Services/Recorder.vala
=> Recorder: Fix potential bugs for null access

src/Application.vala, src/Define.vala, src/MainWindow.vala, src/Views/WelcomeView.vala
Not sure why I use the getter-only property here :shrug:
=> Use const for AUTOSAVE_DISABLED

src/Model/Recorder.vala
=> Recorder: Fix audio stutter after some time

data/reco.desktop.in, src/Application.vala, src/MainWindow.vala
=> Add notification for play and open folder

data/reco.gresource.xml
Forgot to update in dbb3ca43cef0b5e3154c0a5a65dbab3879ffa075
=> gresource: Update prefix for automatic load in Gtk.Application

src/Model/Recorder.vala
=> Recorder: Always use audiomixer to reduce conditions

src/Manager/DeviceManager.vala
- remove meaningless size check before clearing list
- avoid complex conditions
- improve logs
=> refactor: DeviceManager: coding style

build-aux/appcenter/com.github.ryonakano.reco.Devel.yml, com.github.ryonakano.reco.yml
=> Flatpak: Remove unnecessary device access permission

src/Model/Timer/AbstractTimer.vala, src/Widget/LevelBar.vala
- Make sure to initialize timeout variable when it's removed
- Fix substituting signed values to unsigned variables
=> Fix handling timers

src/Model/Recorder.vala
Fixes #294
- Do not inhibit screen lock
- Uninhibit sleep while pausing recording
=> fix: Improve screenlock inhibition

src/MainWindow.vala, src/View/RecordView.vala, src/Widget/LevelBar.vala
LevelBar should be a widget just draw bars every period with a given value; it shouldn't know what the given value is and where it's given from.
=> refactor: LevelBar: Make independent from Recorder

src/MainWindow.vala, src/View/WelcomeView.vala
https://github.com/user-attachments/assets/0e05ff0b-e7e6-4725-8414-de24ed4f19c5
https://github.com/user-attachments/assets/0afe9074-9a0f-454a-a0aa-9817365c2f32
=> fix: Prevent record button from being broken when clicking rapidly

src/MainWindow.vala, src/Model/Recorder.vala
My previous code is terribly hard to understand :weary:
=> refactor: Recorder: Use methods to pause/resume recordings

src/MainWindow.vala
There're no reasons this needs to be translated.
=> feat: Do not translate default filenames

src/View/CountDownView.vala, src/View/RecordView.vala
=> feat: Focus to pause by default to avoid unintentional cancel
